import type { APIRoute } from "astro";
import { SITE_URL } from "../consts";

export const prerender = true;

/**
 * Auto-generated robots.txt — points crawlers at the Astro sitemap index.
 * Sitemap files are produced by @astrojs/sitemap on build.
 */
export const GET: APIRoute = () => {
	const body = `# https://libertta.blog/robots.txt
User-agent: *
Allow: /

# App / private surfaces
Disallow: /api/
Disallow: /*/search/

# Sitemaps (generated by @astrojs/sitemap)
Sitemap: ${SITE_URL}/sitemap-index.xml
`;

	return new Response(body, {
		headers: {
			"Content-Type": "text/plain; charset=utf-8",
			"Cache-Control": "public, max-age=3600",
		},
	});
};
